spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: aanshatem
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: PostgreSQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
